// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRIiF4mNfPFsQW6MsiW8RCPIcFC7DmUc8',
    appId: '1:744438243452:web:a851fe8fd66258c245a9f9',
    messagingSenderId: '744438243452',
    projectId: 'fennechms',
    authDomain: 'fennechms.firebaseapp.com',
    storageBucket: 'fennechms.appspot.com',
    measurementId: 'G-4HFR9D66YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh7QndHXz0eRQ7YyZxoxepB6Qu-F8TTo0',
    appId: '1:744438243452:android:66924134b50eea1c45a9f9',
    messagingSenderId: '744438243452',
    projectId: 'fennechms',
    storageBucket: 'fennechms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH6HgPgZtaSvUQffNr0JSXK2zGB73PrVc',
    appId: '1:744438243452:ios:456161202eef4c3445a9f9',
    messagingSenderId: '744438243452',
    projectId: 'fennechms',
    storageBucket: 'fennechms.appspot.com',
    iosClientId:
        '744438243452-p8co8b5l4firrat593t766ig2s6ike7q.apps.googleusercontent.com',
    iosBundleId: 'com.fennechms.fennechms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH6HgPgZtaSvUQffNr0JSXK2zGB73PrVc',
    appId: '1:744438243452:ios:456161202eef4c3445a9f9',
    messagingSenderId: '744438243452',
    projectId: 'fennechms',
    storageBucket: 'fennechms.appspot.com',
    iosClientId:
        '744438243452-p8co8b5l4firrat593t766ig2s6ike7q.apps.googleusercontent.com',
    iosBundleId: 'com.fennechms.fennechms',
  );
}
